spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_base
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.sboot.springboot_base.entity
  mapper-locations: classpath:mapper/*.xml
